---
##########################################################
# THIS WILL INSTALL JAVA AND DOCKER ON THE PROD MACHINES #
##########################################################
- hosts: prodserver
  become: true
  become_method: sudo
  tasks:
  - name: Install docker
    yum: name=docker state=latest
  - name: Statr the Docker service
    service: name=docker state=started
  - name: Install java
    yum: name=java state=latest
  - name: Create directory for jenkins
    command: mkdir /home/ec2-user/jenkins
  - name: Give permissions to the jenkins directory
    command: chmod 777 /home/ec2-user/jenkins
