---
########################################################################
# THIS WILL INSTALL DOCKER, JAVA AND COPY THE PACKAGE TO THE TEST      #
########################################################################
- hosts: [test-server]
  become: true
  become_method: sudo
  tasks:
  - name: Install docker in the test environment.
    yum: name=docker state=latest
  - name: Start the docker service.
    service: name=docker state=started
  - name: Install java in the test environment.
    yum: name=java state=latest
  - name: copy the package to the test machine
    copy: src=/home/ec2-user/sample-web-app/target/sample-web-app.war dest=/home/ec2-user
    ignore_errors: true
  - name: Copy the dockerfile to the test machine
    copy: src=/etc/ansible/dockerfile dest=/home/ec2-user/
    ignore_erros: true
  - name: Create directory for jenkins
    command: mkdir /home/ec2-user/jenkins
  - name: Give permissions to the jenkins directory
    command: chmod 777 /home/ec2-user/jenkins
